name: Test
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [6.9.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Testing on ${{ matrix.os }} with Node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install
    - run: yarn test
      env:
        CI: 'true'
