name: Test
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Testing on ${{ matrix.os }} with node ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: yarn install
    - run: yarn test --ci
      env:
        CI: 'true'
